### ISSUE TITLE
Make mailto contact links on the jobs board more obvious

### ISSUE THREAD

**Issue by davegurnell** [underscoreio/underscoreio#38]
If a user doesn't have a mail client on their computer, mailto: links may not do anything. The "apply for this job" links on the jobs board are sometimes like this. We should perhaps add some text to the button if the link is a mailto. Something like this:

```
+--------------------------+
|         Apply now        |
| (email dave@example.com) |
+--------------------------+
```

The second line of text should be smaller, and we should add ellipses if it's too long for the button. There's precedent for this in the calls-to-action on the events page.

**Comment by d6y** [comment]
Job board has been removed
